# Permalinks
permalink:              pretty

# Setup
title:                  還沒想到要打什麼名字
tagline:                蹲得越低, 跳得越高
url:
paginate:               5
baseurl:                ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:             _sass
  style:                :compressed

# About/contact
author:
  name:                 Nick
  url:
  email:

# Custom vars
version:                0.0.1
github:
  repo:

# Footer Link
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:               nickhitsai
  instagram:
  linkedin:             nick-hungi-tsai-a74699a2
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
